<?php

use Illuminate\Database\Seeder;

class TreatmentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      // DB::insert("");

      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (1, '', 'Para la crisis nerviosa o también llamado nervios se usa la altamisa en baños por siete dias usando toda la planta')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (2, '', 'Para las heridas se realizan baños con las  hojas de penicilina  por nueve días')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (3, '', 'El pronto alivio se usa en baños por nueve dias usando toda la planta, para aliviar el cansancio muscular')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (4, '', 'Para los colicos menstruales se  prepara primero bebida de eneldo y a esta se le agregan algunas semillas de ámbar maceradas o cocinadas, ya que son muy duras al masticar y se toma por nueve días, un vasito diario')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (5, '', ' En caso de tener erupciones cutaneas como granos, barros, alergias, se tuestan las hojas de venadillo hasta convertirlas en polvo y se aplican en la imperfección por varios dias')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (6, '', 'Para los esguinces se usa la calauala y disciplina en emplastos o maceradas, es decir, se toman las dos plantas, se trituran con una piedra, luego se ponen  en una hojita y  se asan, después se depositan en una telita y se ubican en la parte afectada.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (7, '', 'En caso de sufrir de enfermedades renales, se consumen bebidas de las hojas de oregano silvestre, es decir, se hierve el agua junto con la planta, tres para niños y cinco o seis para dultos y se toman diariamente')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (8, '', 'Se realizan bebidas con las ramitas de borraja, es decir, tallos y hojas, tres ramitas para adultos, una o dos para niños, tres copitas al día, por nueve días o hasta que mejore del asma')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (9, '', 'En caso de erupciones cutaneas como granos, aergias, barros, se realizan bebidas del tallo del trebol rojo, es decir, se pone a hervir el tallo junto con el agua, tres para niños y cinco o seis para dultos y se toman por cinco, siete o nueve días, tres vasitos al día para dultos y tres copitas para niños')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (10, '', 'Para las fiebres muy altas se realizan bebidas con las ramitas de siempre viva, es decir, tallos y hojas, tres ramitas para adultos, una o dos para niños, tres vasitos al día, por tres días ')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (11, '', 'Para los pterigios se depositan nueve espigas de llantén en un frasco blanco y se ponen dos días al sol y uno al sereno, libera una líquido, llamado el espíritu de la planta, de aquí se saca una gota diaria y se aplica en el ojo ')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (12, '', 'Para las crisis nerviosas o también llamadas nervios, se extrae el zumo de las flores de caléndula, poniendolas dos días al sol y uno al sereno, se exprimen y se toman tres gotas por varios días')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (13, '', 'Para la acidez se utiliza la verdolaga en infusión fria, es decir, desde el día anterior se dejan las ramas de la planta en un recipiente con un litro de agua  y al otro día ya se puede usar esta agua, sin necesidad de hervirse, esto se realiza por varios días.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (14, '', 'Para el colesterol alto se puede consumir el coleo directamente con las comidas cocinandolo como si fuera un aliño más o si se prefiere solo.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (15, '', 'Para los esguinces se pisa, se muele y se calienta la planta llamada desinflamadora, y se amarra donde se tenga la molestia hasta que desaparezca')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (16, '', 'Para la odontalgia, dolor de muela y fortalecer los dientes se debe masticar el tallo de limoncillo después de las comidas')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (17, '', 'En caso de presentar dolor en los dientes, odontalgia o querer proteger los dientes se debe masticar las flores de guayaga por cinco minutos después de comer')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (18, '', 'Para la presión arterial alta solo es necesario comer la fruta  de curuba lo más constante posible ')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (19, '', 'Se prepara en infusión con un manojo del pasto micay y se toman tres vasos al día para adultos y tres copitas para niños por nueve días para aliviar el cansancio muscular.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (20, '', 'Para las hemorroides se prepara en infusión las dos plantas, marucha y san juanito, juntas en medio litro de agua y se toma por cucharaditas, por varios días.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (21, '', 'Se utiliza solo la raíz del ribarbo, tostándola hasta convertirla en polvo y se toma en bebidas por varias semanas tres o cuatro vasos al día para curar la anemia')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (22, '', 'Para las crisis nerviosas se prepara el té en sahumerio, es decir, se quema la planta y se absorbe este humo, por nueve dias, se debe hacer en horas de la noche, antes de dormir')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (23, '', 'Para las enfermedades hepáticas se utiliza la fruta de la auyama en jugos por siete días, junto con cola granulada y leche')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (24, '', 'Para el insomnio se hacen inhalaciones de la planta de violeta, primero se pone a herbir con las ramas y se absorbe este humo por varios dias')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (25, '', 'se usan 30 gramos de la sanguinaria menor en infusión en una botella de agua, se cocina por 20 minutos, luego se cuela y se toman 3 copitas al día, esto se hace por nueve días, para la anemia. Se recomienda no comer carne de cerdo ni de res, café, chocolate, mientras se esté consumiendo la planta.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (26, '', 'Para el dolor de cabeza se usan 15 gramos de la hoja de bencenuco en infusión, es decir, se pone a hervir medio litro de agua, se toman tres copitas al día, por nueve días')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (27, '', 'Para la sinusitis se emplea la esponja, se prepara calentando tres hojas bañadas con aguardiente, las inhalan y este olor hace que se desprenda un agua maloliente de la nariz, lo cual indica que si está haciendo efecto, después de hacer las inhalaciones no se debe salir afuera a recibir viento')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (28, '', 'Para la mala digestión o acidez se preparan bebidas de violeta, es decir, se hierven todas las plantas con el agua, con tres hojas o ramitas de las siguientes plantas: yerbabuena, acedera, verdolaga, pata de gallina, se hace en infusión, se prepara por nueve días.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (29, '', 'Se usan tres hojitas para los adultos de salvia china en infusión en una botella de agua, el tratamiento es por nueve días, los primeros cinco días en infusión caliente y los otros cuatro días se prepara hirviendo y se toman cuatro vasitos, esto se usa para el colésterol alto.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (30, '', 'Para las enfermedades de la próstata se toman cinco hojitas de mirto silvestre, se cocinan con medio litro de agua por cinco minutos, se cuelan y luego se toman por nueve días consecutivos, tres vasos al día')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (31, '', 'Para prevenir y curar la caida del cabello y su debilidad se prepara la espuma de mar en infusión con otras plantas, como la melena y cascaras de sauce, en una botella de agua, por veinte días, se toman tres tomas al día.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (32, '', 'Se preparan tres hojitas de curuba en una botella de agua en infusión, cuatro vasos en el día,  si es un niño dos hojitas, cuatro copitas por nueve días, para curar la diabetes')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (33, '', 'se toma una libra del azafran de fruta, se estirpa y se extrae y se toma el jugo en ayunas, por varios días hasta ver mejoria y que haya curado la anemia')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (34, '', 'Se prepara en infusión tres hojas de oregano dulce para mayores en una botella de agua, por nueve días, para niños por cinco días o los adolescentes por siete días, para prevenir y curar la apendicitis')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (35, '', 'Para curar la amigdalitis se toman tres hojas de tomatera con cinco del frijol garbanzo, se ponen a hervir por cinco minutos en una botella de agua, se toman tres cucharadas si son niños menores de 7 años; si son menores de 15 años, tres cucharadas; si son adultos se toman tres copitas por nueve días.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (36, '', 'En caso de presentarse bronquitis es utilizada la aitea o malvisco, para adultos es necesario tomar siete hojitas cocinadas de la planta en una botella de agua por nueve días, si es para niños tres hojitas, en una media botella de agua por cinco días. Al consumirse esta planta no se deben ingerir alimentos condimentados, leche y chocolate.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (37, '', 'Se debe agregar tres hojas de nacedero a la mazamorra y dárselo a las señoras que estén amamantando para aumentar la leche materna o empezar a producir, en caso de que no produzca alimento.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (38, '', 'En caso de padecer de enfermedades hepáticas se debe tomar dos hojitas de cordoncillo en infusión para niños menores de doce años, y cinco hojitas para adultos por nueve días, cuatro vasitos al día.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (39, '', 'Para bajar los niveles de colesterol se cocina una hoja de col y se licua en una botella de agua, y se toman tres cucharadas al día, por cinco días, si son niños; si son adultos tres pocillos pequeños al día')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (40, '', 'Para la neurastenia se toman bebidas de las plantas de aroma junto con el cidrón y melisa, por nueve días, tres vasitos al día.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (41, '', 'Para los granos, barros y purificar la sangre se hacen bebidas con la raíz de caléndula, lavandola muy bien, se toman por siete dias, tres copitas al día')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (42, '', 'Para prevenir el caner y curarlo si no está my avanzado se preparan las hojitas de caléndula en infusión, es decir, se pone a hervir medio litro de agua y cuando hierva se depositan las hojas, cinco hojas para los adultos y para los niños dos o tres, tomándolas diariamente')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (43, '', 'Para las úlceras se utiliza el nabo, para mayores de 20 años se toman dos hojas en infusión, si es para niños media hoja en medio litro de agua, los mayores toman por copas, los niños por cucharaditas')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (44, '', 'Para los lumbagos o también llamados vientos se prepara en bebida la chiva o manrubio con un manojo de eneldo y una cebolla larga, se toman varias cucharadas hasta quitar la molestia')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (45, '', 'para mayores de 20 años se toman dos hojas de nabo en infusión, si es para niños media hoja en medio litro de agua, los mayores toman por copas, los niños por cucharaditas.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (46, '', 'Para la obesidad o soprepeso se prepara unas dos ramitas de manrubio o chiva en bebidas, en un cuarto de litro de agua, y se toma una vez al dia, hasta que llegue a los 55 o 50 kilos.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (47, '', 'Para los cólicos estomacales el limoncillo se prepara en infusión con hierbabuena y manzanilla, en una botella, el tratamiento debe ser en nueve días, tomando tres copitas al día.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (48, '', 'Para la diabetes se cocina una hoja de col  y se licua en una botella de agua, y se toman tres cucharadas al día, por cinco días, si son niños; si son adultos tres pocillos pequeños al día')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (49, '', 'Para la diabetes se utiliza el orégano dulce, tres hojas para mayores en una botella de agua en infusión, por nueve días, para niños por cinco días o los adolescentes por siete días')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (50, '', 'Para la diarrea se usa también la col común, se cocina una hoja y se licua en una botella de agua, y se toman tres cucharadas al día, por cinco días, si son niños; si son adultos tres pocillos pequeños al día')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (51, '', 'Para la diarrea se realizan bebidas de tres hojitas de coleo, por cinco días tres veces al día.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (52, '', 'Para la diarrea, se usa las bebidas de las flores de guayaga, es decir, se hierve la planta junto con el agua, tres veces al día hasta que se quite la diarrea.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (53, '', 'El oregano silvestre se toma en bebidas, tres o cuatro ramitas para adultos, una o dos para niños, por tres o cinco días, para curar la diarrea')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (54, '', 'Para la diarrea o daño de estomago se prepara la verdolaga en infusión fría en un litro de agua, es decir, se deja desde el día anterior en el agua y al otro día se consume sin necesidad de hervirse.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (55, '', 'Para el daño de estomago o diarrea se prepara la violeta en infusión o en bebida hasta que la persona se mejore o también  se pueden hacer inhalaciones,  es decir se hierve la planta y se inhala el humo que libere.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (56, '', 'Para el dolor de cabeza se emplea la planta de té, en sahumerio, es decir, se quema la planta y se absorbe este humo, se realiza el tratamiento por nueve días')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (57, '', 'En caso de padecer enfermedades hepáticas se hace bebida de limoncillo con un poco de bicarbonato de sodio y se toma por nueve días, tres veces al día')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (58, '', 'En caso de enfermedades panreáticas se usa el jugo de la fruta de auyama con cola granulada y leche, consumirlo constantemente, también ayuda como complemento nutricional')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (59, '', 'Para las enfermedades pancreaticas se debe tomar dos hojitas de cordoncillo en infusión para niños menores de doce años, y cinco hojitas para adultos por nueve días, cuatro vasitos al día.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (60, '', 'Para la epilepsia usar en bebidas la espuma de mar tomando cuatro cucharadas en el día por cinco días.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (61, '', 'En caso de padecer epilepsia se toman treinta gramos de la hojita de guadua en infusión y se consumen por nueve días.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (62, '', 'Para las erupciones cutaneas como barros, espinillas, alergias, granos se usan las bebidas de toda la planta de penicilina, ya que purifica la sangre, se usa tres o dos tomas al día por nueve días.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (63, '', 'Para la fiebre se emplea el pasto micay, se prepara en infusión en una botella de agua, se toman tres vasitos al día por tres días.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (64, '', 'En caso de tener fiebre se utilza el trebol rojo,  se prepara en infusión o en bebidas por nueve días, agregando unas cuantas ramas de la planta.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (65, '', 'Para las fiebres se emplea la albahaca blanca,  se prepara en bebidas, tres veces al día o en baños hasta que baje la fiebre.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (66, '', 'Se usa la borraja para bajar las fiebres en bebidas, tres veces al día hasta que se mejore')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (67, '', 'Para bajar las fiebres es recomendable bebidas de coleo, tres copitas al día por siete días.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (68, '', 'En caso de presentarse gastritis se prepara el coleo en bebidas por nueve días o se puede consumir directamente cocido en las ensaladas')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (69, '', 'Para la gastritis se usa el té en bebida por nueve días en tiempo de menguante, tres veces al día')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (70, '', 'Para las heridas se usa las hojas de la planta de  veronica en baños por siete o nueve días')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (71, '', 'Para las heridas se usa la desinflamadora,  se pisa, se muele y se calienta, y se la amarra donde se tenga la molestia y ayuda a aliviarla')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (72, '', 'En caso de presentarse heridas se realizan baños de toda la planta de amor seco, hasta que mejore la apariencia')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (73, '', 'Para las inflamaciones se emplea la desinflamadora, se pisa, se muele y se calienta, y se la amarra donde se tenga la molestia y la desinflama')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (74, '', 'En caso de presentarse inflamaciones se usa la planta de penicilina en baños por siete días')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (75, '', 'Para las inflamaciones hacerse baños de amor seco por siete o nueve días')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (76, '', 'En caso de inflamaciones se realizan baños de la planta de veronica, por  siete o nueve días')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (77, '', 'Para las hinchazones en los pezones se hacen baños con las hojas de auyama, hasta que la hinchazón en los pezones disminuya')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (78, '', 'Para el malestar general se realizan bebidas de tres ramitas de hierbabueba, se toman tres tasitas al día y se realiza el tratamiento hasta ver mejoria')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (79, '', 'Para la migraña se hacen baños con una buena cantidad de las ramitas de té, por nueve días, para complementar también se pueden hacer sahumerios cuando esté pasando por el dolor intenso de cabeza')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (80, '', 'Para la neuragia se toman 15 gramos  de la planta de bencenuco, los cuales se ponen a hervir, se cuela, se envasa y se toman tres copitas al día, en niños es de cinco días el tratamiento, en adultos entre siete y nueve días.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (81, '', 'En caso de soprepeso y obesidad consumir la guadua, se toman treinta gramos de la hojita en infusión y se consumen por nueve días, una sola vez al día.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (82, '', 'Se usa el polvo de  la raíz de riobarbo para curar y prevenir el  paludismo, se prepara en bebidas y se toman siete a nueve días tres veces al día, para extarer el polvo de debe triturar y licuar.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (83, '', 'Para la presión arterial alta se emplea el trébol rojo, se prepara en infusión y en bebidas por nueve días.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (84, '', 'En caso de tener la presión arterial alta se debe consumir el pasto micay, en bebidas, se prepara en infusión en una botella de agua y se toma por siete días')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (85, '', 'La col común se usa para bajar la presión arterial alta, se cocina una hoja y se licua en una botella de agua, y se toman tres cucharadas al día, por cinco días, si son niños; si son adultos tres pocillos pequeños al día')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (86, '', 'La venturosa se prepara en baños de toda la planta, hasta que calmen los dolores de reumatismo')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (87, '', 'Para el reumatismo se prepara pronto alivio en baños diariamente hasta que desaparezca el dolor')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (88, '', 'Para los trigliceridos altos se hacen baños de bastantes hojas de cofrey, por nueve días, se descansa una semana y se vuelve a iniciar.')");
      DB::insert("INSERT INTO treatments (id, name, procedure) VALUES (89, '', 'Para el acne y purificar la sangre se puede usar la cola de caballo en baños después del baño habitual, no tiene necesidad de hervirse, simplemente desde el día anterior se pone en un recipiente con agua remojando y al otro día ya se puede usar.')");
    }
}
